### PR TITLE
added forgot password screen and button 

### LINKED ISSUE #47: Add a forget password page
**Is your feature request related to a problem? Please describe.**
I don't remember my password and I don't know how to log in

**Describe the solution you'd like**

- [x] Add a forget password page
- [x] button in login page to get to it

### PR DESCRIPTION
**Pull request by WaniAthar**
# Description

added forgot password page 
created button for forgot password

### CODE REVIEW

**Review by hayat-tamboli — APPROVED** [review]
great work

**Comment by hayat-tamboli** [comment]
Fixed #47

**Comment by WaniAthar** [comment]
@hayat-tamboli @Manas1820 thanks

**Comment by Manas1820** [comment]
Great job

**Pull request merged**
